DROP DATABASE IF EXISTS Employee;
CREATE DATABASE Employee;

USE Employee;

CREATE TABLE department (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT primary key,
  name VARCHAR SELCT 30 UNIQUE 'NOT NULL'
);
CREATE TABLE role (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR SELECT 30 UNIQUE 'NOT NULL',
  salary DECIMAL UNSIGNED 'NOT NULL',
  department_id INT 'UNSIGNED' 'NOT NULL'
);
CREATE TABLE employee (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR SELECT 30 'NOT NULL',
  last_name VARCHAR SELECT 30 'NOT NULL',
  role_id INT UNSIGNED NOT NULL,
  manager_id INT 'UNSIGNED'
);